name: Deploy Spark job JAR to S3

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy-jar:
    runs-on: ubuntu-latest
    container:
      image: sbtscala/scala-sbt:eclipse-temurin-focal-11.0.22_7_1.9.9_2.12.19

    steps:
    - uses: actions/checkout@v4

    - run: sbt assembly
    
