name: Deploy Spark job JAR to S3

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AWS_REGION: "us-east-1"
  AWS_ACCOUNT_ID: "117819748843"

jobs:
  deploy-jar:
    runs-on: ubuntu-latest
    container:
      image: sbtscala/scala-sbt:eclipse-temurin-focal-11.0.22_7_1.9.9_2.12.19

    steps:
    - uses: actions/checkout@v4
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - run: sbt assembly

    - run: aws s3 cp target/scala-*/* s3://deployment-zone-117819748843/availity_assessment/
